sudo: required
dist: trusty
language: c
before_script:
  - export LC_ALL=C LC_TYPE=C LANG=
  - sudo apt-get install debian-archive-keyring
  - echo 'deb http://ftp.de.debian.org/debian/ sid main' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install -yy build-essential colorgcc dpkg-dev debhelper dh-autoreconf fakeroot git-buildpackage
  - git fetch origin +upstream:upstream
  - git fetch origin +pristine-tar:pristine-tar
script: >
  gbp buildpackage --git-builder="debuild --set-envvar=CC=$TRAVIS_CC --no-lintian -i'^\.git/|^\.gitignore$|^\.travis.yml$|^README\.md$' -I" -uc -us &&
  cat ../*.changes &&
  debc &&
  lintian --dont-check-part standards-version --fail-on-warnings --color always --info ../*.changes &&
  sudo dpkg --install ../*.deb
env:
  global:
    - TRAVIS_CC=colorgcc
    - DEB_BUILD_OPTIONS='parallel=4'
    - LINTIAN_PROFILE=debian
