#!/bin/sh
set -e

#DEBHELPER#

# This code was taken from nss-mdns:

log() {
    echo "$*"
}

remove_nss_entry() {
    log "Checking NSS setup..."
    # abort if /etc/nsswitch.conf does not exist
    if ! [ -e /etc/nsswitch.conf ]; then
        log "Could not find /etc/nsswitch.conf."
        return
    fi
    sed -E -i /etc/nsswitch.conf \
        -e 's/^(hosts:.*)(\s+docker(\s+\[NOTFOUND=return\])?)(.*)$/\1\4/g'
}

action="$1"

if [ "$action" = remove ]; then
    remove_nss_entry
fi
