#!/bin/sh
set -e

#DEBHELPER#

# This code was taken from nss-mdns:

log() {
    echo "$*"
}

remove_nss_entry() {
    log "Checking NSS setup..."
    # abort if /etc/nsswitch.conf does not exist
    if ! [ -e /etc/nsswitch.conf ]; then
        log "Could not find /etc/nsswitch.conf."
        return
    fi
    perl -i -pe '
        sub remove {
            my $s = shift;
            $s =~ s/\s+docker(\s+\[NOTFOUND=return\])?//g;
            return $s;
        }
        s/^(hosts:)(.*)/$1.remove($2)/e;
    ' /etc/nsswitch.conf
}

action="$1"

if [ "$action" = remove ]; then
    remove_nss_entry
fi
